// Normalizes data/raw/*.json into src/data/parking.kw.json and writes data/REPORT.md.
// Fails without writing anything if any record can't be parsed and has no override.
// Usage: npm run data:build
import { writeFile } from 'node:fs/promises';
import { buildDataset, serializeDataset, type DatasetBuild } from '../src/data/dataset.ts';
import type { DatasetId } from '../src/data/types.ts';
import { DATASET_FILE, REPORT_FILE, loadRawLayers } from './raw-layers.ts';

const build = buildDataset(await loadRawLayers());

if (build.errors.length > 0) {
  console.error(
    `Data build failed with ${String(build.errors.length)} error(s).\n` +
      'Fix the parser in src/data/ or add an entry to src/data/overrides.ts:\n',
  );
  for (const error of build.errors) console.error(`  - ${error}`);
  process.exit(1);
}

await writeFile(DATASET_FILE, serializeDataset(build.dataset));
await writeFile(REPORT_FILE, renderReport(build));

const { options } = build.dataset;
console.log(
  `Wrote ${String(options.length)} parking options (${String(build.excluded.length)} excluded, ` +
    `${String(build.overridden.length)} overridden).`,
);

function renderReport({ dataset, excluded, overridden }: DatasetBuild): string {
  const datasetOf = (id: string): DatasetId =>
    id.startsWith('kitchener-street-')
      ? 'kitchener-on-street'
      : id.startsWith('kitchener-lot-')
        ? 'kitchener-public-lots'
        : 'waterloo-city-lots';
  const cell = (value: string | number | null) => String(value ?? '—').replaceAll('|', '\\|');
  const row = (...cells: (string | number | null)[]) => `| ${cells.map(cell).join(' | ')} |`;

  const yearCounts = new Map<string, number>();
  for (const option of dataset.options) {
    const year = option.override ? 'overridden' : (option.source.updated?.slice(0, 4) ?? 'unknown');
    yearCounts.set(year, (yearCounts.get(year) ?? 0) + 1);
  }

  const optionsById = new Map(dataset.options.map((o) => [o.id, o]));

  return [
    '# Parking data build report',
    '',
    'Generated by `npm run data:build`; do not edit by hand.',
    '',
    '## Sources',
    '',
    row('Dataset', 'Publisher', 'Layer last edited', 'Included', 'Excluded'),
    row('---', '---', '---', '---', '---'),
    ...dataset.sources.map((s) =>
      row(
        s.name,
        s.publisher,
        s.lastEdited,
        dataset.options.filter((o) => o.source.dataset === s.dataset).length,
        excluded.filter((e) => datasetOf(e.id) === s.dataset).length,
      ),
    ),
    '',
    `Options with unverified rules (no confirmed pricing, must not rank as free): ${String(dataset.options.filter((o) => o.rulesStatus === 'unverified').length)}`,
    '',
    '## Rules last updated (year of source record, or overridden)',
    '',
    row('Year', 'Options'),
    row('---', '---'),
    ...[...yearCounts.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([year, n]) => row(year, n)),
    '',
    `## Overrides (${String(overridden.length)})`,
    '',
    row('Id', 'Name', 'Reason', 'Source', 'Checked'),
    row('---', '---', '---', '---', '---'),
    ...overridden.map((id) => {
      const option = optionsById.get(id);
      return row(id, option?.name ?? '(excluded)', option?.override?.reason ?? 'Excluded by override', option?.override?.sourceUrl ?? null, option?.override?.checked ?? null);
    }),
    '',
    `## Excluded records (${String(excluded.length)})`,
    '',
    row('Id', 'Name', 'Reason'),
    row('---', '---', '---'),
    ...excluded.map((e) => row(e.id, e.name, e.reason)),
    '',
  ].join('\n');
}
